spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/financial?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081
swagger:
  groupName: manager
  backPackage: com.spring4all.manager.controller